import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './components/navbar/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'More Fit',
	description: 'Generated by create next app',
}

// async function fetchPosts () {
// 	const response = await fetch("https://jsonplaceholder.typicode.com/posts", {
// 		cache: "no-store",
// 	});
// 	return response.json();
// };

async function fetchPosts () {
	try {

		const response = await fetch("http://127.0.0.1:8000/api/auth", {
			cache: "no-store",
		});
		console.log(response);
		return response.json();
	}catch(e) {
		console.log(e);
	}
};


export default async function RootLayout({
	children,
}: {
  children: React.ReactNode
}) {
	const data = await fetchPosts();
	console.log(data);
	return (
		<html lang="en">
			<body className={inter.className}>
				{children}
			</body>
		</html>
	)
}
