import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/app/components/navbar/navbar'
import { API_URL } from '@/app/utils/constants'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'More Fit',
	description: 'Generated by create next app',
}

// FIXME: on production, verify URL
async function getAuth() {
	console.log("getAuth", API_URL)
	return fetch(`${API_URL}/auth`, {
		cache: "no-store",
	}).then(res => res.json()).then(data => {
		if (data.auth) return true;
		return false;
	});
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	const auth = await getAuth();
	return (
		<html lang="en">
			<body className={inter.className}>
				<Navbar auth={auth}/>
				<main>{children}</main>
			</body>
		</html>
	)
}
