import { Metadata } from "next"
import Navbar from "../components/navbar/navbar"

// export const metadata: Metadata = {
// 	title: 'More Fit - Auth',
// 	description: 'Generated by create next app',
// }

export async function generateMetadata() {
	return { title: 'More fit - Auth'}
}

export default function AuthLayout({children}:{children: React.ReactNode}) {
	return <main> {children} </main>
}